import { ArmorClass, Age, BuildingType, Resource, TechId, UnitType } from '../shared/enums';
import { FARM_FOOD } from '../shared/constants';
import type { BuildingStats } from '../shared/content-types';

const DROPOFF_ALL =
  (1 << Resource.Food) | (1 << Resource.Wood) | (1 << Resource.Gold) | (1 << Resource.Stone); // 15

// Base (unmodified) building stats — single source of truth from contentDesign.
// buildTicks are total villager-work ticks; attacks are ALWAYS pierce (Arrow) for buildings.
// Effective per-player stats (cost discounts) come from resolveBuildingStats(); never mutate.
export const BUILDING_STATS: Readonly<Record<BuildingType, BuildingStats>> = {
  [BuildingType.TownCenter]: {
    name: 'Town Center',
    cost: { food: 0, wood: 275, gold: 0, stone: 100 },
    buildTicks: 3000,
    hp: 2400,
    meleeArmor: 3,
    pierceArmor: 5,
    sizeX: 4,
    sizeY: 4,
    los: 8,
    attack: 5,
    attackRange: 6,
    attackRateTicks: 40,
    popProvided: 5,
    dropOff: DROPOFF_ALL,
    trains: [UnitType.Villager],
    researches: [TechId.Loom, TechId.Wheelbarrow, TechId.FeudalAge, TechId.CastleAge, TechId.ImperialAge],
    requiresAge: Age.Dark,
    requiresBuilding: -1,
    armorClasses: ArmorClass.Building,
    storesFood: 0,
  },
  [BuildingType.House]: {
    name: 'House',
    cost: { food: 0, wood: 25, gold: 0, stone: 0 },
    buildTicks: 500,
    hp: 550,
    meleeArmor: 0,
    pierceArmor: 7,
    sizeX: 2,
    sizeY: 2,
    los: 4,
    attack: 0,
    attackRange: 0,
    attackRateTicks: 0,
    popProvided: 5,
    dropOff: 0,
    trains: [],
    researches: [],
    requiresAge: Age.Dark,
    requiresBuilding: -1,
    armorClasses: ArmorClass.Building,
    storesFood: 0,
  },
  [BuildingType.Mill]: {
    name: 'Mill',
    cost: { food: 0, wood: 100, gold: 0, stone: 0 },
    buildTicks: 700,
    hp: 600,
    meleeArmor: 0,
    pierceArmor: 7,
    sizeX: 2,
    sizeY: 2,
    los: 4,
    attack: 0,
    attackRange: 0,
    attackRateTicks: 0,
    popProvided: 0,
    dropOff: 1 << Resource.Food,
    trains: [],
    researches: [],
    requiresAge: Age.Dark,
    requiresBuilding: -1,
    armorClasses: ArmorClass.Building,
    storesFood: 0,
  },
  [BuildingType.LumberCamp]: {
    name: 'Lumber Camp',
    cost: { food: 0, wood: 100, gold: 0, stone: 0 },
    buildTicks: 700,
    hp: 600,
    meleeArmor: 0,
    pierceArmor: 7,
    sizeX: 2,
    sizeY: 2,
    los: 4,
    attack: 0,
    attackRange: 0,
    attackRateTicks: 0,
    popProvided: 0,
    dropOff: 1 << Resource.Wood,
    trains: [],
    researches: [],
    requiresAge: Age.Dark,
    requiresBuilding: -1,
    armorClasses: ArmorClass.Building,
    storesFood: 0,
  },
  [BuildingType.MiningCamp]: {
    name: 'Mining Camp',
    cost: { food: 0, wood: 100, gold: 0, stone: 0 },
    buildTicks: 700,
    hp: 600,
    meleeArmor: 0,
    pierceArmor: 7,
    sizeX: 2,
    sizeY: 2,
    los: 4,
    attack: 0,
    attackRange: 0,
    attackRateTicks: 0,
    popProvided: 0,
    dropOff: (1 << Resource.Gold) | (1 << Resource.Stone),
    trains: [],
    researches: [],
    requiresAge: Age.Dark,
    requiresBuilding: -1,
    armorClasses: ArmorClass.Building,
    storesFood: 0,
  },
  [BuildingType.Farm]: {
    name: 'Farm',
    cost: { food: 0, wood: 60, gold: 0, stone: 0 },
    buildTicks: 300,
    hp: 480,
    meleeArmor: 0,
    pierceArmor: 0,
    sizeX: 2,
    sizeY: 2,
    los: 2,
    attack: 0,
    attackRange: 0,
    attackRateTicks: 0,
    popProvided: 0,
    dropOff: 0,
    trains: [],
    researches: [],
    requiresAge: Age.Dark,
    requiresBuilding: BuildingType.Mill,
    armorClasses: ArmorClass.Building,
    storesFood: FARM_FOOD,
  },
  [BuildingType.Barracks]: {
    name: 'Barracks',
    cost: { food: 0, wood: 175, gold: 0, stone: 0 },
    buildTicks: 1000,
    hp: 1200,
    meleeArmor: 1,
    pierceArmor: 7,
    sizeX: 3,
    sizeY: 3,
    los: 5,
    attack: 0,
    attackRange: 0,
    attackRateTicks: 0,
    popProvided: 0,
    dropOff: 0,
    trains: [UnitType.Militia, UnitType.ManAtArms, UnitType.Spearman],
    researches: [TechId.ManAtArmsUpgrade],
    requiresAge: Age.Dark,
    requiresBuilding: -1,
    armorClasses: ArmorClass.Building,
    storesFood: 0,
  },
  [BuildingType.ArcheryRange]: {
    name: 'Archery Range',
    cost: { food: 0, wood: 175, gold: 0, stone: 0 },
    buildTicks: 1000,
    hp: 1200,
    meleeArmor: 1,
    pierceArmor: 7,
    sizeX: 3,
    sizeY: 3,
    los: 5,
    attack: 0,
    attackRange: 0,
    attackRateTicks: 0,
    popProvided: 0,
    dropOff: 0,
    trains: [UnitType.Archer],
    researches: [],
    requiresAge: Age.Feudal,
    requiresBuilding: BuildingType.Barracks,
    armorClasses: ArmorClass.Building,
    storesFood: 0,
  },
  [BuildingType.Stable]: {
    name: 'Stable',
    cost: { food: 0, wood: 175, gold: 0, stone: 0 },
    buildTicks: 1000,
    hp: 1200,
    meleeArmor: 1,
    pierceArmor: 7,
    sizeX: 3,
    sizeY: 3,
    los: 5,
    attack: 0,
    attackRange: 0,
    attackRateTicks: 0,
    popProvided: 0,
    dropOff: 0,
    trains: [UnitType.ScoutCavalry, UnitType.Knight],
    researches: [],
    requiresAge: Age.Feudal,
    requiresBuilding: BuildingType.Barracks,
    armorClasses: ArmorClass.Building,
    storesFood: 0,
  },
  [BuildingType.Blacksmith]: {
    name: 'Blacksmith',
    cost: { food: 0, wood: 150, gold: 0, stone: 0 },
    buildTicks: 800,
    hp: 1000,
    meleeArmor: 1,
    pierceArmor: 7,
    sizeX: 3,
    sizeY: 3,
    los: 5,
    attack: 0,
    attackRange: 0,
    attackRateTicks: 0,
    popProvided: 0,
    dropOff: 0,
    trains: [],
    researches: [
      TechId.Forging,
      TechId.IronCasting,
      TechId.Fletching,
      TechId.BodkinArrow,
      TechId.ScaleMailArmor,
      TechId.ChainMailArmor,
      TechId.ScaleBardingArmor,
    ],
    requiresAge: Age.Feudal,
    requiresBuilding: -1,
    armorClasses: ArmorClass.Building,
    storesFood: 0,
  },
  [BuildingType.Castle]: {
    name: 'Castle',
    cost: { food: 0, wood: 0, gold: 0, stone: 650 },
    buildTicks: 4000,
    hp: 4800,
    meleeArmor: 8,
    pierceArmor: 11,
    sizeX: 4,
    sizeY: 4,
    los: 10,
    attack: 11,
    attackRange: 8,
    attackRateTicks: 40,
    popProvided: 0,
    dropOff: 0,
    trains: [], // trains CIVS[player.civ].uniqueUnit via the canTrain rule in content/stats.ts
    researches: [],
    requiresAge: Age.Castle,
    requiresBuilding: -1,
    armorClasses: ArmorClass.Building,
    storesFood: 0,
  },
};
