import { ArmorClass, Age, BuildingType, ProjectileType, TechId, UnitType } from '../shared/enums';
import type { UnitStats } from '../shared/content-types';

// Base (unmodified) unit stats. Numbers are the single source of truth from the design's
// contentDesign block. Times are in TICKS (20/s); speed is tiles/sec (resolvers divide by
// TICK_RATE); costs are absolute (civ/tech cost modifiers are applied by content/stats.ts).
// Effective, per-player stats come from resolveUnitStats(); NEVER mutate these objects.
export const UNIT_STATS: Readonly<Record<UnitType, UnitStats>> = {
  [UnitType.Villager]: {
    name: 'Villager',
    cost: { food: 50, wood: 0, gold: 0, stone: 0 },
    popCost: 1,
    trainTicks: 500,
    trainedAt: BuildingType.TownCenter,
    requiresAge: Age.Dark,
    requiresTech: -1,
    hp: 25,
    attack: 3,
    attackIsPierce: false,
    attackRange: 0,
    attackRateTicks: 40,
    meleeArmor: 0,
    pierceArmor: 0,
    speedTilesPerSec: 1.0,
    los: 4,
    radius: 0.3,
    armorClasses: ArmorClass.Villager,
    bonuses: [{ classMask: ArmorClass.Building, amount: 3 }],
    projectile: -1,
    projectileSpeed: 0,
  },
  [UnitType.Militia]: {
    name: 'Militia',
    cost: { food: 60, wood: 0, gold: 20, stone: 0 },
    popCost: 1,
    trainTicks: 420,
    trainedAt: BuildingType.Barracks,
    requiresAge: Age.Dark,
    requiresTech: -1,
    hp: 40,
    attack: 4,
    attackIsPierce: false,
    attackRange: 0,
    attackRateTicks: 40,
    meleeArmor: 0,
    pierceArmor: 1,
    speedTilesPerSec: 0.9,
    los: 4,
    radius: 0.3,
    armorClasses: ArmorClass.Infantry,
    bonuses: [],
    projectile: -1,
    projectileSpeed: 0,
  },
  [UnitType.ManAtArms]: {
    name: 'Man-at-Arms',
    cost: { food: 60, wood: 0, gold: 20, stone: 0 },
    popCost: 1,
    trainTicks: 420,
    trainedAt: BuildingType.Barracks,
    requiresAge: Age.Feudal,
    requiresTech: TechId.ManAtArmsUpgrade,
    hp: 45,
    attack: 6,
    attackIsPierce: false,
    attackRange: 0,
    attackRateTicks: 40,
    meleeArmor: 0,
    pierceArmor: 1,
    speedTilesPerSec: 0.9,
    los: 4,
    radius: 0.3,
    armorClasses: ArmorClass.Infantry,
    bonuses: [],
    projectile: -1,
    projectileSpeed: 0,
  },
  [UnitType.Spearman]: {
    name: 'Spearman',
    cost: { food: 35, wood: 25, gold: 0, stone: 0 },
    popCost: 1,
    trainTicks: 440,
    trainedAt: BuildingType.Barracks,
    requiresAge: Age.Feudal,
    requiresTech: -1,
    hp: 45,
    attack: 3,
    attackIsPierce: false,
    attackRange: 0,
    attackRateTicks: 60,
    meleeArmor: 0,
    pierceArmor: 0,
    speedTilesPerSec: 1.0,
    los: 4,
    radius: 0.3,
    armorClasses: ArmorClass.Infantry,
    bonuses: [{ classMask: ArmorClass.Cavalry, amount: 15 }],
    projectile: -1,
    projectileSpeed: 0,
  },
  [UnitType.Archer]: {
    name: 'Archer',
    cost: { food: 0, wood: 25, gold: 45, stone: 0 },
    popCost: 1,
    trainTicks: 700,
    trainedAt: BuildingType.ArcheryRange,
    requiresAge: Age.Feudal,
    requiresTech: -1,
    hp: 30,
    attack: 4,
    attackIsPierce: true,
    attackRange: 4,
    attackRateTicks: 40,
    meleeArmor: 0,
    pierceArmor: 0,
    speedTilesPerSec: 0.96,
    los: 6,
    radius: 0.3,
    armorClasses: ArmorClass.Archer,
    bonuses: [],
    projectile: ProjectileType.Arrow,
    projectileSpeed: 7,
  },
  [UnitType.ScoutCavalry]: {
    name: 'Scout Cavalry',
    cost: { food: 80, wood: 0, gold: 0, stone: 0 },
    popCost: 1,
    trainTicks: 600,
    trainedAt: BuildingType.Stable,
    requiresAge: Age.Dark,
    requiresTech: -1,
    hp: 45,
    attack: 3,
    attackIsPierce: false,
    attackRange: 0,
    attackRateTicks: 40,
    meleeArmor: 0,
    pierceArmor: 2,
    speedTilesPerSec: 1.55,
    los: 8,
    radius: 0.3,
    armorClasses: ArmorClass.Cavalry,
    bonuses: [],
    projectile: -1,
    projectileSpeed: 0,
  },
  [UnitType.Knight]: {
    name: 'Knight',
    cost: { food: 60, wood: 0, gold: 75, stone: 0 },
    popCost: 1,
    trainTicks: 600,
    trainedAt: BuildingType.Stable,
    requiresAge: Age.Castle,
    requiresTech: -1,
    hp: 100,
    attack: 10,
    attackIsPierce: false,
    attackRange: 0,
    attackRateTicks: 36,
    meleeArmor: 2,
    pierceArmor: 2,
    speedTilesPerSec: 1.35,
    los: 4,
    radius: 0.3,
    armorClasses: ArmorClass.Cavalry,
    bonuses: [],
    projectile: -1,
    projectileSpeed: 0,
  },
  [UnitType.Longbowman]: {
    name: 'Longbowman',
    cost: { food: 0, wood: 35, gold: 40, stone: 0 },
    popCost: 1,
    trainTicks: 360,
    trainedAt: BuildingType.Castle,
    requiresAge: Age.Castle,
    requiresTech: -1,
    hp: 35,
    attack: 6,
    attackIsPierce: true,
    attackRange: 5,
    attackRateTicks: 38,
    meleeArmor: 0,
    pierceArmor: 0,
    speedTilesPerSec: 0.96,
    los: 7,
    radius: 0.3,
    armorClasses: ArmorClass.Archer | ArmorClass.UniqueUnit,
    bonuses: [],
    projectile: ProjectileType.Arrow,
    projectileSpeed: 7,
  },
  [UnitType.ThrowingAxeman]: {
    name: 'Throwing Axeman',
    cost: { food: 55, wood: 0, gold: 25, stone: 0 },
    popCost: 1,
    trainTicks: 340,
    trainedAt: BuildingType.Castle,
    requiresAge: Age.Castle,
    requiresTech: -1,
    hp: 60,
    attack: 7,
    attackIsPierce: false, // Axe deals MELEE-type damage at range
    attackRange: 3,
    attackRateTicks: 40,
    meleeArmor: 0,
    pierceArmor: 0,
    speedTilesPerSec: 1.0,
    los: 5,
    radius: 0.3,
    armorClasses: ArmorClass.Infantry | ArmorClass.UniqueUnit,
    bonuses: [],
    projectile: ProjectileType.Axe,
    projectileSpeed: 5,
  },
  [UnitType.Mangudai]: {
    name: 'Mangudai',
    cost: { food: 0, wood: 55, gold: 65, stone: 0 },
    popCost: 1,
    trainTicks: 520,
    trainedAt: BuildingType.Castle,
    requiresAge: Age.Castle,
    requiresTech: -1,
    hp: 60,
    attack: 6,
    attackIsPierce: true,
    attackRange: 4,
    attackRateTicks: 42,
    meleeArmor: 0,
    pierceArmor: 1,
    speedTilesPerSec: 1.45,
    los: 6,
    radius: 0.3,
    armorClasses: ArmorClass.Archer | ArmorClass.Cavalry | ArmorClass.UniqueUnit,
    bonuses: [],
    projectile: ProjectileType.Arrow,
    projectileSpeed: 7,
  },
  [UnitType.Sheep]: {
    name: 'Sheep',
    cost: { food: 0, wood: 0, gold: 0, stone: 0 },
    popCost: 0,
    trainTicks: 0,
    trainedAt: -1,
    requiresAge: Age.Dark,
    requiresTech: -1,
    hp: 8,
    attack: 0,
    attackIsPierce: false,
    attackRange: 0,
    attackRateTicks: 0,
    meleeArmor: 0,
    pierceArmor: 0,
    speedTilesPerSec: 0,
    los: 2,
    radius: 0.3,
    armorClasses: 0,
    bonuses: [],
    projectile: -1,
    projectileSpeed: 0,
  },
};
